### ISSUE TITLE
Github not work

### ISSUE THREAD

**Issue by Mte90** [evilsocket/emoticode#2]
When i try to login or sign with github i am redirected to http://www.emoticode.net/auth/failure?message=invalid_credentials&strategy=github
I don't understand the problem :-/

**Comment by evilsocket** [comment]
plase, logout from github, login to github and try again

**Comment by Mte90** [comment]
uhm same problem :-/

**Comment by evilsocket** [comment]
could you please retry now?

**Comment by Mte90** [comment]
now i am redirect to the page of gituhb, after pressed the button allow access i am redirect to http://www.emoticode.net/auth/failure?message=invalid_credentials&strategy=github

**Comment by evilsocket** [comment]
https://github.com/intridea/omniauth-github/issues/12 ... I have to wait until they push those changes in the stable branch.
