### ISSUE TITLE
Strange highlight

### ISSUE THREAD

**Issue by Mte90** [evilsocket/emoticode#5]
I see that in soem snippet http://www.emoticode.net/php/add-tinymce-by-id.html or http://www.emoticode.net/php/has_oembed_youtube.html the code is grey like the comment.
It's possible use a different color?

**Comment by evilsocket** [comment]
it depends on the grammar css file, I will check this ASAP

**Comment by evilsocket** [comment]
should be fixed with https://github.com/evilsocket/emoticode/commit/02485054659c9cd3e5909361087a78e850daf43e
