### ISSUE TITLE
Markdown preview it's not the same of the snippet

### ISSUE THREAD

**Issue by Mte90** [evilsocket/emoticode#6]
I've insert in the description text like function_that_do_it_something, in the preview no problem, in the snippet page break the formatting.
I've fixed with `function_that_do_it_something` but i think that is a problem.

**Comment by evilsocket** [comment]
it's not a problem, the underscore _ has a special meaning in markdown language, therefore you need to use the backtick character as you actually did :)

**Comment by Mte90** [comment]
Why the preview work and in the frontend create this problem?

**Comment by evilsocket** [comment]
because in the preview there's no markdown parsing, it's just stripped text :)
